apiVersion: apps/v1
kind: Deployment
metadata:
  name: logserver-deploy
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logserver
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1      
  template:
    metadata:
      name: logserver
      labels:
        app: logserver
    spec:
      containers:
        - name: logservercon
          image: datalust/seq:latest
          ports:
            - containerPort: 80  
          env:
            - name: ACCEPT_EULA
              value: "Y"

---
apiVersion: v1
kind: Service
metadata:
  name: logserver
  namespace: ingress-nginx
spec:
  type: ClusterIP
  ports:
  - name: "http-5341"
    port: 5341
    targetPort: 80
  selector:
    app: logserver
    

