apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailserver-deploy
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailserver
  template:
    metadata:
      name: mailserver
      labels:
        app: mailserver
    spec:
      containers:
        - name: mailservercon
          image: maildev/maildev:1.1.0
          ports:
            - containerPort: 25 
            - containerPort: 80  

---
apiVersion: v1
kind: Service
metadata:
  name: mailserver-service
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
  - name: "smtp"
    port: 25
    targetPort: 25
  - name: "web"
    port: 4000
    targetPort: 80
    nodePort: 30002
  selector:
    app: mailserver


