---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: ebs-sc
  namespace: ingress-nginx
provisioner: ebs.csi.aws.com
volumeBindingMode: Immediate
allowVolumeExpansion: true


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: ingress-nginx
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserverdata-pvc
  namespace: ingress-nginx 
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 1Gi
